import type { ResolvedAntdvVersionEnv } from '../src/types'
import process from 'node:process'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import { buildIssueUrl, collectAntdvEnv, createIssueBody } from '../src/utils/issue'

const mocks = vi.hoisted(() => ({
  getInstalledPackageVersion: vi.fn(),
  getPackageManagerVersion: vi.fn(),
  platform: vi.fn(() => 'test-platform'),
  release: vi.fn(() => 'test-release'),
}))

vi.mock('@/commands/env.ts', () => ({
  getInstalledPackageVersion: mocks.getInstalledPackageVersion,
}))

vi.mock('@/utils/env.ts', () => ({
  getPackageManagerVersion: mocks.getPackageManagerVersion,
}))

vi.mock('node:os', () => ({
  platform: mocks.platform,
  release: mocks.release,
}))

const env: ResolvedAntdvVersionEnv = {
  vue: '3.5.21',
  vite: '7.1.5',
  antdv: '1.2.3',
  cli: '0.0.0',
  typescript: '5.9.2',
  system: 'darwin 24.6.0',
  package: {
    node: '22.19.0',
    npm: '10.9.3',
    pnpm: '10.15.1',
    deno: '2.4.5',
    bun: '1.2.21',
  },
}

beforeEach(() => {
  mocks.getInstalledPackageVersion.mockReset().mockResolvedValue(null)
  mocks.getPackageManagerVersion.mockReset().mockResolvedValue('0.0.0')
  mocks.platform.mockClear()
  mocks.release.mockClear()
})

describe('collectAntdvEnv', () => {
  it('collects dependency, package manager, runtime, system, and CLI versions', async () => {
    mocks.getInstalledPackageVersion
      .mockResolvedValueOnce('1.2.3')
      .mockResolvedValueOnce('3.5.21')
      .mockResolvedValueOnce('7.1.5')
      .mockResolvedValueOnce('5.9.2')
    mocks.getPackageManagerVersion
      .mockResolvedValueOnce('10.9.3')
      .mockResolvedValueOnce('10.15.1')
      .mockResolvedValueOnce('2.4.5')
      .mockResolvedValueOnce('1.2.21')

    await expect(collectAntdvEnv('/project')).resolves.toEqual({
      antdv: '1.2.3',
      vue: '3.5.21',
      vite: '7.1.5',
      typescript: '5.9.2',
      package: {
        node: process.versions.node,
        npm: '10.9.3',
        pnpm: '10.15.1',
        deno: '2.4.5',
        bun: '1.2.21',
      },
      system: 'test-platform test-release',
      cli: '0.0.0',
    })

    expect(mocks.getInstalledPackageVersion).toHaveBeenNthCalledWith(1, '/project', 'antdv-next')
    expect(mocks.getInstalledPackageVersion).toHaveBeenNthCalledWith(2, '/project', 'vue')
    expect(mocks.getInstalledPackageVersion).toHaveBeenNthCalledWith(3, '/project', 'vite')
    expect(mocks.getInstalledPackageVersion).toHaveBeenNthCalledWith(4, '/project', 'typescript')
    expect(mocks.getPackageManagerVersion).toHaveBeenNthCalledWith(1, '/project', 'npm')
    expect(mocks.getPackageManagerVersion).toHaveBeenNthCalledWith(2, '/project', 'pnpm')
    expect(mocks.getPackageManagerVersion).toHaveBeenNthCalledWith(3, '/project', 'deno')
    expect(mocks.getPackageManagerVersion).toHaveBeenNthCalledWith(4, '/project', 'bun')
  })

  it('uses unknown when an expected dependency is not installed', async () => {
    const result = await collectAntdvEnv('/missing-dependencies')

    expect(result).toMatchObject({
      antdv: 'unknown',
      vue: 'unknown',
      vite: 'unknown',
      typescript: 'unknown',
    })
  })
})

describe('createIssueBody', () => {
  it('creates the complete issue template and appends extra information', () => {
    const body = createIssueBody({
      reproduction: 'https://example.com/reproduction',
      steps: '1. Open the reproduction\n2. Click the button',
      expected: 'The dialog opens.',
      actual: 'Nothing happens.',
      extra: 'This only happens after a page refresh.',
      env,
    })

    expect(body).toBe(`### Reproduction link

[https://example.com/reproduction](https://example.com/reproduction)

### Steps to reproduce

1. Open the reproduction
2. Click the button

### What is expected?

The dialog opens.

### What is actually happening?

Nothing happens.

| Environment | Info |
| --- | --- |
| Vue | 3.5.21 |
| Vite | 7.1.5 |
| Antdv | 1.2.3 |
| TypeScript | 5.9.2 |
| Cli | 0.0.0 |
| Node | 22.19.0 |
| Npm | 10.9.3 |
| Pnpm | 10.15.1 |
| System | darwin 24.6.0 |

---
This only happens after a page refresh.

---
<sub>Generated by [@antdv-next/cli](https://github.com/antdv-next/cli)</sub>`)
  })

  it.each([
    {
      name: 'CodeSandbox',
      link: 'https://codesandbox.io/p/sandbox/antdv-demo',
      markdown: '[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/p/sandbox/antdv-demo)',
    },
    {
      name: 'StackBlitz',
      link: 'https://stackblitz.com/edit/antdv-demo',
      markdown: '[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](https://stackblitz.com/edit/antdv-demo)',
    },
    {
      name: 'an empty reproduction',
      link: '',
      markdown: '',
    },
  ])('renders $name link correctly', ({ link, markdown }) => {
    const body = createIssueBody({
      reproduction: link,
      steps: 'Reproduce the issue.',
      expected: 'Expected result.',
      actual: 'Actual result.',
      extra: '',
      env,
    })

    expect(body).toContain(`### Reproduction link\n\n${markdown}\n\n### Steps to reproduce`)
  })

  it('does not add an empty extra-information section', () => {
    const body = createIssueBody({
      reproduction: '',
      steps: 'Reproduce the issue.',
      expected: 'Expected result.',
      actual: 'Actual result.',
      extra: '',
      env,
    })

    expect(body.match(/^---$/gm)).toHaveLength(1)
    expect(body.endsWith('<sub>Generated by [@antdv-next/cli](https://github.com/antdv-next/cli)</sub>')).toBe(true)
  })
})

describe('buildIssueUrl', () => {
  it('builds a GitHub new-issue URL with encoded title and body', () => {
    const result = buildIssueUrl(
      'Button: click & focus',
      'antdv-next/antdv-next',
      'Expected = open\nActual = closed',
    )
    const url = new URL(result)

    expect(url.origin).toBe('https://github.com')
    expect(url.pathname).toBe('/antdv-next/antdv-next/issues/new')
    expect(url.searchParams.get('title')).toBe('Button: click & focus')
    expect(url.searchParams.get('body')).toBe('Expected = open\nActual = closed')
  })

  it('truncates an oversized encoded body and preserves a useful suffix', () => {
    const body = '% &=中文\n'.repeat(2_000)
    const result = buildIssueUrl('Large issue', 'antdv-next/antdv-next', body)
    const parsedBody = new URL(result).searchParams.get('body') ?? ''
    const truncationNote = '\n\n(Content truncated. Please add remaining details after opening.)'
    const retainedBody = parsedBody.slice(0, -truncationNote.length)

    expect(result.length).toBeLessThanOrEqual(8_000)
    expect(result.length).toBeGreaterThan(7_900)
    expect(parsedBody.endsWith(truncationNote)).toBe(true)
    expect(retainedBody.length).toBeLessThan(body.length)
    expect(body.startsWith(retainedBody)).toBe(true)
  })
})
