import type { AntdvIssueFields, ResolvedAntdvVersionEnv } from '@/types.ts'
import { platform, release } from 'node:os'
import process from 'node:process'
import { getInstalledPackageVersion } from '@/commands/env.ts'
import { getPackageManagerVersion } from '@/utils/env.ts'

const MAX_URL_LENGTH = 8000

export const collectAntdvEnv = async (cwd: string): Promise<ResolvedAntdvVersionEnv> => {
  return {
    antdv: await getInstalledPackageVersion(cwd, 'antdv-next') || 'unknown',

    vue: await getInstalledPackageVersion(cwd, 'vue') || 'unknown',
    vite: await getInstalledPackageVersion(cwd, 'vite') || 'unknown',

    typescript: await getInstalledPackageVersion(cwd, 'typescript') || 'unknown',
    package: {
      node: process.versions.node,
      npm: await getPackageManagerVersion(cwd, 'npm'),
      pnpm: await getPackageManagerVersion(cwd, 'pnpm'),
      deno: await getPackageManagerVersion(cwd, 'deno'),
      bun: await getPackageManagerVersion(cwd, 'bun'),
    },
    system: `${platform()} ${release()}`,
    cli: __CLI_VERSION__,
  }
}

export const createIssueBody = ({ reproduction, steps, expected, actual, extra, env }: AntdvIssueFields): string => {
  const { vue, vite, antdv, cli, typescript, system } = env
  const { npm, pnpm, node } = env.package

  let body = `### Reproduction link

${createReproductionLink(reproduction)}

### Steps to reproduce

${steps}

### What is expected?

${expected}

### What is actually happening?

${actual}

| Environment | Info |
| --- | --- |
| Vue | ${vue} |
| Vite | ${vite} |
| Antdv | ${antdv} |
| TypeScript | ${typescript} |
| Cli | ${cli} |
| Node | ${node} |
| Npm | ${npm} |
| Pnpm | ${pnpm} |
| System | ${system} |

`.trim()

  if (extra) {
    body += [
      '\n',
      '---',
      extra,
    ].join('\n')
  }

  body += [
    '\n',
    '---',
    '<sub>Generated by [@antdv-next/cli](https://github.com/antdv-next/cli)</sub>',
  ].join('\n')
  return body
}

function createReproductionLink(link: string): string {
  if (!link) {
    return ''
  }

  if (link.includes('codesandbox.io')) {
    return `[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](${link})`
  }
  else if (link.includes('stackblitz.com')) {
    return `[![Edit on StackBlitz](https://developer.stackblitz.com/img/open_in_stackblitz.svg)](${link})`
  }

  return `[${link}](${link})`
}

export function buildIssueUrl(title: string, repo: string, body: string): string {
  const baseUrl = `https://github.com/${repo}/issues/new`
  const params = new URLSearchParams({ title, body })
  let url = `${baseUrl}?${params.toString()}`

  if (url.length > MAX_URL_LENGTH) {
    const truncationNote = '\n\n(Content truncated. Please add remaining details after opening.)'
    let lo = 0
    let hi = body.length
    while (lo < hi) {
      const mid = Math.ceil((lo + hi) / 2)
      const truncated = body.slice(0, mid) + truncationNote
      const testParams = new URLSearchParams({ title, body: truncated })
      const testUrl = `${baseUrl}?${testParams.toString()}`
      if (testUrl.length <= MAX_URL_LENGTH) {
        lo = mid
      }
      else {
        hi = mid - 1
      }
    }
    const truncatedBody = body.slice(0, lo) + truncationNote
    const finalParams = new URLSearchParams({ title, body: truncatedBody })
    url = `${baseUrl}?${finalParams.toString()}`
  }

  return url
}
